config/routes.rb
Setlist::Application.routes.draw do
  get "profiles/show"

  resources :statuses

  devise_for :users

  root :to => 'static_pages#home'

  devise_scope :user do
    get '/signup',       to: 'devise/registrations#new'
    get '/signin',       to: 'devise/sessions#new'
    get '/logout',       to: 'devise/sessions#destroy'
    get '/edit_account', to: 'devise/registrations#edit'
    get '/cancel',       to: 'devise/registrations#cancel'
    get '/statuses',     to: 'statuses#index'
    get '/new_status',   to: 'statuses#new'
    get '/status',       to: 'statuses#show'
    get '/:id',          to: 'profiles#show'
  end
  

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/models/status.rb
class Status < ActiveRecord::Base
  attr_accessible :content, :user_id
  belongs_to :user
  # belongs_to is found at api.rubyonrails.org 

  validates :content, presence: true,
                      length: { minimum: 2 }

  validates :user_id, presence: true  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,
                  :first_name, :last_name, :profile_name
  # attr_accessible :title, :body

  validates :first_name, presence: true 
  validates :last_name, presence: true
  validates :profile_name, presence: true, 
                           uniqueness: true,
                           format:  {
                             with: /^[a-zA-Z0-9_-]+$/,
                             message: "Registration must be formatted correctly."
                           }

  has_many :statuses

  def full_name
    first_name + " " + last_name
  end

  def gravatar_url
    stripped_email = email.strip 
    downcased_email = stripped_email.downcase 
    hash = Digest::MD5.hexdigest(downcased_email)

    "http://gravatar.com/avatar/#{hash}"
  end

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || stored_location_for(resource) || statuses_path
  end


end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = User.find_by_profile_name(params[:id])
    if @user 
      @statuses = @user.statuses.all 
      render action: :show 
    else
      render file: 'public/404', status: 404, formats: [:html]
    end
  end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @statuses }
    end
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
    @status = Status.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/new
  # GET /statuses/new.json
  def new
    @status = Status.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/1/edit
  def edit
    @status = Status.find(params[:id])
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(params[:status])

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render json: @status, status: :created, location: @status }
      else
        format.html { render action: "new" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /statuses/1
  # PUT /statuses/1.json
  def update
    @status = Status.find(params[:id])

    respond_to do |format|
      if @status.update_attributes(params[:status])
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status = Status.find(params[:id])
    @status.destroy

    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Setlist"
    if page_title.empty?
      base_title 
    else
      "#{base_title} | #{page_title}"
    end
  end


end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper

  

end

app/helpers/users_helper.rb
module UsersHelper
  

end

app/views/layouts/_alerts.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success">      
    <%= flash[:notice] %>
  </div>
<% elsif flash[:alert] %>
  <div class="alert alert-error">      
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <div><%= link_to image_tag("cbsBanner125px.png", alt: "Setlist Application"), about_path %></div>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Help",    help_path %></li> 
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "News",    "https://www.facebook.com/colin.stodd" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Setlist.", root_path, id: "logo" %>
      <nav>        
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <!-- above button is for collapse purposes -->
        <div class="collapse navbar-collapse dropdown-toggle" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">          
            <li><%= link_to "Setlists", statuses_path %></li>
            <li><%= %></li>
            <li><%= render 'devise/shared/login_items' %></li>
            <li><%= render 'devise/shared/registration_items' %></li>
          </ul>
        </div>        
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
  <!-- [if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>

  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= render 'layouts/alerts' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>

app/views/profiles/show.html.erb
<% provide(:title, "Profiles") %>

<h1><%= @user.full_name %></h1>

<% if @statuses %>
  <% @statuses.each do |status| %>
  <div class="well">
    <%= status.content %>
    <hr />
    <%= link_to time_ago_in_words(status.created_at), status_path(status) %> ago
  </div>
  <% end %>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About us") %>

<h1>About page</h1>
<p>
  Welcome to the About page, Setlist is an application that allows <br />
   bands and fans to easily draft setlists for their shows.  
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>

<h1>Contact page</h1>
<p>
  Please <a href="mailto:cbstodd@gmail.com">contact</a> the developer if you have any questions.
</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title) %>

<div class="center jumbotron">
  <h1>Setlist.</h1>
  <p><h2>Welcome to the Setlist Application</h2></p>

  <%= link_to "Sign up/in now!", signup_path, class: "btn btn-large btn-danger", id: "button" %> 
</div>

app/views/statuses/_form.html.erb
<%= simple_form_for(@status, html: {class: "form-vertical jumbotron"}) do |f| %> 
  <div class="field">
    <%= f.input :user_id, collection: User.all, label_method: :full_name %>
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit "Post", class: "btn btn-large btn-danger" %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<% provide(:title, "Edit profile") %>

<h1>Edit profile info</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<% provide(:title, "All Setlists") %>

<h1>All Setlists</h1>

<div class="push">
  <%= link_to "Post a new setlist", new_status_path, class: "btn btn-danger" %>
</div>
<% @statuses.each do |status| %>
  <div class="media pull-left">
    <div class="media-object">
        <%= image_tag status.user.gravatar_url, class: "gravatar" %>
      </div>
    </div>
  <div class="media">
    <div class="media-heading">        
      <strong><%= status.user.full_name %></strong>
      <p><%= status.content %></p>
      <div class="meta">
        <%= link_to time_ago_in_words(status.created_at) + " ago", status %>
        <span class="admin">
          <%= link_to "Edit", edit_status_path(status) %> |
          <%= link_to "Delete", status, method: :delete, data: {confirm: "Are you sure you want to delete this status?"} %>
        </span>
      </div>
    </div>
  </div>  


<% end %>

app/views/statuses/new.html.erb
<% provide(:title, "New Setlist ") %>

<h1>Post new setlist</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<% provide(:title, "Setlists") %>

<h1>All Setlists</h1>

<p>
  <b>Name</b>
  <%= @status.user.full_name %>
</p>
<p>
  <b>Content</b>
  <%= @status.content %>
</p>


<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>

<h1>Sign up</h1>
<p>Please sign up to start using the Setlist Application</p>